apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-secrets
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  BETTER_AUTH_SECRET: {{ .Values.backend.env.BETTER_AUTH_SECRET | b64enc | quote }}
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | b64enc | quote }}
  RESEND_API_KEY: {{ .Values.backend.env.RESEND_API_KEY | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.backend.env.OPENAI_API_KEY | b64enc | quote }}